## Import Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns


In [2]:
df = pd.read_csv("grid_power.csv")

## VIEW DATA

In [3]:
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [4]:
df.shape


(10000, 14)

In [5]:
df.describe()

tau1          tau2          tau3          tau4            p1  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean       5.250000      5.250001      5.250004      5.249997      3.750000   
std        2.742548      2.742549      2.742549      2.742556      0.752160   
min        0.500793      0.500141      0.500788      0.500473      1.582590   
25%        2.874892      2.875140      2.875522      2.874950      3.218300   
50%        5.250004      5.249981      5.249979      5.249734      3.751025   
75%        7.624690      7.624893      7.624948      7.624838      4.282420   
max        9.999469      9.999837      9.999450      9.999443      5.864418   

                 p2            p3            p4            g1            g2  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean      -1.250000     -1.250000     -1.250000      0.525000      0.525000   
std        0.433035      0.433035      0.433035      0.274256      0.274255   
min       -1.999891     -1.999945     -1.999926      0.050009      0.050053   
25%       -1.624901     -1.625025     -1.624960      0.287521      0.287552   
50%       -1.249966     -1.249974     -1.250007      0.525009      0.525003   
75%       -0.874977     -0.875043     -0.875065      0.762435      0.762490   
max       -0.500108     -0.500072     -0.500025      0.999937      0.999944   

                 g3            g4          stab  
count  10000.000000  10000.000000  10000.000000  
mean       0.525000      0.525000      0.015731  
std        0.274255      0.274255      0.036919  
min        0.050054      0.050028     -0.080760  
25%        0.287514      0.287494     -0.015557  
50%        0.525015      0.525002      0.017142  
75%        0.762440      0.762433      0.044878  
max        0.999982      0.999930      0.109403

In [6]:
df.drop(columns=["stab"], axis=1, inplace=True)

In [7]:
df.stabf.value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [8]:
x = df.drop(columns=["stabf"], axis=1)
y = df["stabf"]
display(x)

y

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4  
0    -1.723086  0.650456  0.859578  0.887445  0.958034  
1    -1.255012  0.413441  0.862414  0.562139  0.781760  
2    -0.920492  0.163041  0.766689  0.839444  0.109853  
3    -0.997374  0.446209  0.976744  0.929381  0.362718  
4    -0.554305  0.797110  0.455450  0.656947  0.820923  
...        ...       ...       ...       ...       ...  
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  
9996 -1.733414  0.502079  0.567242  0.285880  0.366120  
9997 -1.975373  0.487838  0.986505  0.149286  0.145984  
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  

[10000 rows x 12 columns]

0       unstable
1         stable
2       unstable
3       unstable
4       unstable
          ...   
9995    unstable
9996      stable
9997      stable
9998    unstable
9999    unstable
Name: stabf, Length: 10000, dtype: object

In [11]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)
y

array([1, 0, 1, ..., 0, 1, 1], dtype=int64)

## Prepare the test data

## Model Building

In [12]:
from sklearn.model_selection import train_test_split
x_train,  x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 1)

In [14]:
from sklearn.preprocessing import StandardScaler
# define standard  scaler
scaler = StandardScaler().fit(x_train)
x_train = scaler.transform(x_train)

x_test = scaler.transform(x_test)

C:\Users\User\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


In [24]:
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from lightgbm import LGBMClassifier

lg_model = LGBMClassifier()
lg_model.fit(x_train, y_train)
my_model = xgb.XGBClassifier()
my_model.fit(x_train, y_train)
rf = RandomForestClassifier()
rf.fit(x_train,y_train) 

rf_preds = rf.predict(x_test) 
lg_preds = lg_model.predict(x_test)
xg_preds = my_model.predict(x_test)

In [25]:
x_test, preds

(array([[6.87787559, 4.11381956, 9.35676782, ..., 0.84553616, 0.11244008,
         0.82256228],
        [5.80284119, 6.2713711 , 4.73153955, ..., 0.41647845, 0.91284617,
         0.8613062 ],
        [2.28699798, 4.38514242, 2.83023162, ..., 0.13018574, 0.70388734,
         0.06381067],
        ...,
        [7.84894484, 0.68488886, 0.72822334, ..., 0.55979884, 0.68241816,
         0.88690215],
        [2.17396654, 5.77679709, 4.59763847, ..., 0.74310343, 0.15216124,
         0.30518262],
        [1.46761767, 9.38908499, 6.01974032, ..., 0.27321693, 0.52614488,
         0.85116334]]),
 array([1, 1, 1, ..., 1, 1, 1], dtype=int64))

In [28]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix

accuracy = accuracy_score(y_true=y_test, y_pred=xg_preds)
accuracy#prints 53.0

0.644

## Feature Importance

In [35]:
from sklearn.ensemble import ExtraTreesClassifier

extra_tree_forest = ExtraTreesClassifier(n_estimators = 5, scoring = 'accuracy', n_jobs = -1, verbose = 1,random_state = 1)
  
# Training the model
extra_tree_forest.fit(x_train, y_train)
  



TypeError: __init__() got an unexpected keyword argument 'scoring'